[project]
name = "vscode-docs-ja"
version = "0.1.0"
description = "Japanese translation of microsoft/vscode-docs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "markdown-callouts>=0.4.0",
    "mdx-truly-sane-lists>=1.3",
    "mkdocs-material[imaging]==9.5.35",
]
