[project]
name = "vscode-docs-ja"
version = "0.1.0"
description = "Japanese translation of microsoft/vscode-docs"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "markdown-callouts>=0.4.0",
    "mkdocs-material[imaging]>=9.5.43",
    "mkdocs-open-in-new-tab>=1.0.7",
]
