name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: apt-get install pngquant
      - name: mkdocs build
        run: |
          gh auth setup-git
          uv run --with "git+$MKDOCS_MATERIAL_INSIDERS_GIT_URL" mkdocs build --strict
        env:
          GH_TOKEN: ${{ secrets.MKDOCS_MATERIAL_INSIDERS_TOKEN }}
          MKDOCS_MATERIAL_INSIDERS_GIT_URL: ${{ vars.MKDOCS_MATERIAL_INSIDERS_GIT_URL }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    permissions:
      id-token: write
      pages: write
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - id: deployment
        uses: actions/deploy-pages@v4
